GET http://localhost:8000/p

###Signup
POST http://localhost:8000/signup
Content-Type: application/json

{"username": "ashishk",
"password": "Dilscoop1",
"firstname": "Ashish",
"lastname": "Karn"
}

###Login 
POST http://localhost:8000/login
Content-Type: application/json

{
"username": "ashishk",
"password": "Dilscoop1",
"firstname": "Ashish",
"lastname": "Karn"
}

###Logout
GET http://localhost:8000/logout

###
GET http://localhost:8000/profile/